#!/bin/sh

if [ -z $1 ]
then
	echo "usage: mkrelease revision\nFor example ./mkrelease 0.4-1"; exit
fi

project=flyhigh
revision=$1
curDir=`pwd`
workDir=$curDir/$project.$revision

# tag and get source on CVS
cvstag="version_`echo $revision | sed s/"\."/_/`"
echo "cvs -z3 -d:ext:grafal@flyhigh.cvs.sourceforge.net:/cvsroot/flyhigh rtag $cvstag $project"
cvs -z3 -d:ext:grafal@flyhigh.cvs.sourceforge.net:/cvsroot/flyhigh rtag $cvstag $project
echo "cvs -z3 -d:ext:grafal@flyhigh.cvs.sourceforge.net:/cvsroot/flyhigh checkout -d $project.$revision -r $cvstag $project"
cvs -z3 -d:ext:grafal@flyhigh.cvs.sourceforge.net:/cvsroot/flyhigh checkout -d $project.$revision -r $cvstag $project

# create configure
echo "make --directory=$workDir -f Makefile.cvs"
make --directory=$workDir -f Makefile.cvs

# create source tar
echo "tar -czf $project.$revision.tar.gz $workDir"
tar -czf $curDir/$project.$revision.tar.gz $workDir
mv $curDir/$project.$revision.tar.gz $workDir

# configure and build
mkdir $workDir/release
cd $workDir/release
$workDir/configure
make
echo "strip $workDir/release/src/$project"
strip $workDir/release/src/$project

# prepare debian archive
mkdir -p $workDir/debian/usr/bin/
cp $workDir/release/src/$project $workDir/debian/usr/bin/

mkdir -p $workDir/debian/usr/share/flyhigh/
cp $workDir/doc/sql/flyhigh.sql $workDir/debian/usr/share/flyhigh/
cp $workDir/tools/xtrSwiss100 $workDir/debian/usr/share/flyhigh/
cp $workDir/src/images/flyhigh.png $workDir/debian/usr/share/flyhigh/

mkdir -p $workDir/debian/usr/share/doc/flyhigh/
cp $workDir/doc/flyhigh $workDir/debian/usr/share/doc/flyhigh/

mkdir -p $workDir/debian/usr/share/applications/
cp $workDir/src/flyhigh.desktop $workDir/debian/usr/share/applications/

# remove disturbing dirs
rm -r $workDir/debian/DEBIAN/CVS/

# fill control file
projectsize="`du -sb $workDir/debian/usr/ | awk '{print $1}'`"
cat $workDir/debian/DEBIAN/control.template | sed s/Version:/"Version: $revision"/ | sed s/Installed-Size:/"Installed-Size: $projectsize"/ > $workDir/debian/DEBIAN/control

# create debian archive
dpkg --build $workDir/debian/ $workDir/$project.$revision.deb
