#!/bin/sh

prefix=$1
directories="\
	usr/ \
	usr/share/ \
	usr/share/applications/ \
	usr/share/doc/ \
	usr/share/doc/flyhigh \
	usr/share/flyhigh/ \
	usr/share/man/ \
	usr/bin/"

for directory in $directories
do
	[ -x $prefix/$directory ] || mkdir $prefix/$directory
done

cp ./release/src/flyhigh $prefix/usr/bin/
cp ./src/flyhigh.desktop $prefix/usr/share/applications/
cp ./src/images/flyhigh.png $prefix/usr/share/flyhigh/
cp ./doc/sql/flyhigh.sql $prefix/usr/share/flyhigh/
cp ./doc/flyhigh $prefix/usr/share/doc/flyhigh/

#dpkg-deb --build debian
#mv debian.deb flyhigh.deb
