

#ifndef QEXTSERIALPORT_GLOBAL_H
#define QEXTSERIALPORT_GLOBAL_H

#include <QtCore/qglobal.h>

// no need for Q_DECL_EXPORT/_IMPORT
//#ifdef QEXTSERIALPORT_LIB
//# define QEXTSERIALPORT_EXPORT Q_DECL_EXPORT
//#else
//# define QEXTSERIALPORT_EXPORT Q_DECL_IMPORT
//#endif
# define QEXTSERIALPORT_EXPORT

#endif // QEXTSERIALPORT_GLOBAL_H

