GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE, ALTER ON *.* TO 'flyhigh'@'localhost' IDENTIFIED BY 'flyhigh';

CREATE DATABASE IF NOT EXISTS `flyhigh_v2` DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
USE `flyhigh_v2`;

CREATE TABLE IF NOT EXISTS `Gliders`
(
	`Id` INT NULL AUTO_INCREMENT,
	`Manufacturer` VARCHAR(16) CHARACTER SET utf8 NULL DEFAULT '',
	`Model` VARCHAR(16) CHARACTER SET utf8 NOT NULL,
	`Serial` VARCHAR(16) CHARACTER SET utf8 NULL DEFAULT '',
	PRIMARY KEY(`Id`),
	UNIQUE KEY(`Manufacturer`, `Model`, `Serial`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `Pilots`
(
	`Id` INT NULL AUTO_INCREMENT,
	`FirstName` VARCHAR(16) CHARACTER SET utf8 NOT NULL,
	`LastName` VARCHAR(16) CHARACTER SET utf8 NOT NULL,
	`BirthDate` DATE NULL DEFAULT '0000-00-00',
	`CallSign` VARCHAR(16) CHARACTER SET utf8 NOT NULL,
	`GliderId` INT NULL DEFAULT '0',
	PRIMARY KEY(`Id`),
	UNIQUE KEY byPilot(`FirstName`, `LastName`, `BirthDate`),
	FOREIGN KEY(`GliderId`) REFERENCES Gliders(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `WayPoints`
(
	`Id` INT NULL AUTO_INCREMENT,
	`Name` VARCHAR(16) NOT NULL,
	`Spot` VARCHAR(16) NULL DEFAULT '',
	`Country` VARCHAR(2) NULL DEFAULT '',
	`Longitude` FLOAT NOT NULL,
	`Latitude` FLOAT NOT NULL,
	`Altitude` INT NOT NULL,
	`Description` VARCHAR(200) NULL DEFAULT '',
	PRIMARY KEY(`Id`),
	UNIQUE KEY byWayPoints(`Name`, `Spot`, `Country`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `Flights`
(
	`Id` INT NULL AUTO_INCREMENT,
	`Number` INT NOT NULL,
	`PilotId` INT NOT NULL,
	`Date` DATE NOT NULL,
	`Time` TIME NOT NULL,
	`GliderId` INT NOT NULL,
	`StartPtId` INT NOT NULL,
	`LandPtId` INT NOT NULL,
	`Duration` INT NOT NULL,
	`Distance` INT NOT NULL,
	`Comment` VARCHAR(500) NULL DEFAULT '',
	`IGCFile` MEDIUMBLOB,
	PRIMARY KEY(`Id`),
	UNIQUE KEY byFlight(`PilotId`, `Number`),
	FOREIGN KEY(`PilotId`) REFERENCES Pilots(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY(`GliderId`) REFERENCES Gliders(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY(`StartPtId`) REFERENCES WayPoints(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY(`LandPtId`) REFERENCES WayPoints(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `Routes`
(
	`Id` INT NULL AUTO_INCREMENT,
  `Name` VARCHAR(16) NOT NULL,
	`Type` INT NULL DEFAULT 0,
	PRIMARY KEY(`Id`),
	UNIQUE KEY byRoutes(`Name`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `RouteItems`
(
	`Id` INT NULL AUTO_INCREMENT,
	`RouteId` INT NOT NULL,
	`WayPointId` INT NOT NULL,
	PRIMARY KEY(`Id`),
	FOREIGN KEY(`RouteId`) REFERENCES Routes(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY(`WayPointId`) REFERENCES WayPoints(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `Servicings`
(
	`Id` INT NULL AUTO_INCREMENT,
	`GliderId` INT NOT NULL,
	`Date` DATE NOT NULL,
	`Responsibility` VARCHAR(16) NOT NULL,
	`Comment` VARCHAR(200) NULL DEFAULT '',
	PRIMARY KEY(`Id`),
	FOREIGN KEY(`GliderId`) REFERENCES Gliders(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `LastModified`
(
	`Id` INT NULL AUTO_INCREMENT,
	`Name` VARCHAR(16) NOT NULL,
	`Time` datetime NOT NULL,
	PRIMARY KEY(`Id`),
	UNIQUE KEY (`Name`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

INSERT INTO `LastModified` (`Id`, `Name`, `Time`) VALUES
(1, 'Pilots', '1970-01-01 00:00:00'),
(2, 'Flights', '1970-01-01 00:00:00'),
(3, 'Gliders', '1970-01-01 00:00:00'),
(4, 'Servicings', '1970-01-01 00:00:00'),
(5, 'WayPoints', '1970-01-01 00:00:00'),
(6, 'DataBaseVersion', '2011-01-18 00:00:00'),
(7, 'Routes', '1970-01-01 00:00:00');
