#!/bin/bash

. /usr/share/debconf/confmodule

set -e

case "$1" in
	configure)
		# Compatibility symlinks into /usr/doc
		echo "Setup flyhigh SQL database"
		mysql -u root -p < /usr/share/flyhigh/flyhigh.sql
		;;
	*)
		#
		# Unknown action - do nothing.
		#
		exit 0
		;;
esac
